services:
  backend:
    container_name: study-k3s-deployment-backend-dev
    image: chocobe/k3s-backend-dev
    build:
      # context 에 상대 경로를 입력할 경우, 현재 docker-compose.yaml 파일의 경로를 기준으로 함
      context: ../..
      # dockerfile 에 상대 경로를 입력할 경우, context 의 경로를 기준으로 함
      dockerfile: ./docker/dev/backend.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - study-k3s-deployment-backend-dev-node_modules:/app/node_modules
      - ../../backend:/app

  frontend:
    container_name: study-k3s-deployment-frontend-dev
    image: chocobe/k3s-frontend-dev
    build:
      # context 에 상대 경로를 입력할 경우, 현재 docker-compose.yaml 파일의 경로를 기준으로 함
      context: ../..
      # dockerfile 에 상대 경로를 입력할 경우, context 의 경로를 기준으로 함
      dockerfile: ./docker/dev/frontend.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - study-k3s-deployment-frontend-dev-node_modules:/app/node_modules
      - ../../frontend:/app

volumes:
  study-k3s-deployment-backend-dev-node_modules:
  study-k3s-deployment-frontend-dev-node_modules:
